version: '3.8'

services:
  dbt:
    build:
      context: .
    container_name: dbt
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - ~/.dbt:/root/.dbt
    environment:
      - DBT_PROFILES_DIR=/usr/app