data_elt_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      port: 5442
      user: postgres
      password: postgres
      dbname: data-elt
      schema: dw_raw
      threads: 1
