version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./airbyte/migrations/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    networks:
      - data-elt-network

  api:
    container_name: data-elt-api
    ports:
      - 8081:8080
    image: data-elt-api:bin
    volumes:
      - /var/log/container:/var/log/
    env_file:
      - files/env/.env  # Reference the .env file
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
    depends_on:
      - db
    networks:
      - data-elt-network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data


volumes:
  db:
    driver: local
  minio_data:

networks:
  data-elt-network:
    driver: bridge