version: '3.2'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"
    volumes: 
      - db:/var/lib/postgresql/data

  api:
    container_name: data-elt-api
    ports:
      - 8081:8080
    image: data-elt-api:bin
    volumes:
      - /var/log/container:/var/log/
    env_file:
      - files/env/.env  # Reference the .env file
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
    depends_on:
      - db

volumes:
  db:
    driver: local
