openapi: 3.1.0
info:
  contact:
    email: rifkiadrn12@gmail.com
    name: Rifki Adrian
  description: |2-
    Open API specification which describes the API for Data ELT
  title:
    Data ELT API
  version: 1.0.0

servers:
  - url: /

paths:
  /auth/login:
    $ref: './paths/auth.yaml'
  /users:
    $ref: './paths/user.yaml'

components:
  securitySchemes:
    BearerAuth:
      $ref: './components/securities/bearer_auth.yaml'
    ApiKeyAuth:
      $ref: './components/securities/api_key_auth.yaml'
  schemas:
    LoginUser:
      $ref: './components/schemas/login_user.yaml'
    LoginResponse:
      $ref: './components/schemas/login_response.yaml'
    User: 
      $ref: './components/schemas/user.yaml'
    RegisterUser:
      $ref: './components/schemas/register_user.yaml'

security:
  - BearerAuth: []
  - ApiKeyAuth: []