// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package model

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token JWT token for authentication
	Token string `json:"token"`
	User  User   `json:"user"`
}

// LoginUser defines model for LoginUser.
type LoginUser struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterUser defines model for RegisterUser.
type RegisterUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	CreatedAt int64  `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Password  string `json:"password"`
	Token     string `json:"token"`
	UpdatedAt int64  `json:"updated_at"`
	Username  string `json:"username"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginUser

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterUser
